# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  release:
    types: [ published ]
  push:
    tags:
      - 'v*'  # 仅在标签匹配 'v*' 模式时触发

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: 🐼 Set up JDK 18
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'adopt'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

      # Runs a single command using the runners shell
    - name: 🔥 publishing surgery-helper
      run: |
        chmod +x gradlew
        ./gradlew :surgery-helper:publishSurgeryPublicationToGithubPackagesRepository
      env:
        GITHUB_USER: ${{ secrets.NAME_GITHUB }}
        GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}

      # Runs a single command using the runners shell
    - name: 🔥 publishing surgery-api
      run: |
        chmod +x gradlew
        ./gradlew :surgery-api:publishSurgeryPublicationToGithubPackagesRepository
      env:
        GITHUB_USER: ${{ secrets.NAME_GITHUB }}
        GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}

    - name: 🔥 publishing surgery-doctor-arouter
      run: |
        chmod +x gradlew
        ./gradlew :surgery-doctor-arouter:publishSurgeryPublicationToGithubPackagesRepository
      env:
        GITHUB_USER: ${{ secrets.NAME_GITHUB }}
        GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}

    - name: 🔥 publishing surgery-doctor-tryfinally
      run: |
        chmod +x gradlew
        ./gradlew :surgery-doctor-tryfinally:publishSurgeryPublicationToGithubPackagesRepository
      env:
        GITHUB_USER: ${{ secrets.NAME_GITHUB }}
        GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}

    - name: 🔥 publishing surgery-doctors
      run: |
        chmod +x gradlew
        ./gradlew :surgery-doctors:publishSurgeryPublicationToGithubPackagesRepository
      env:
        GITHUB_USER: ${{ secrets.NAME_GITHUB }}
        GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}

    - run: echo "🎉 The job finish publish all succeed."